# Generated by Django 6.0.4 on 2026-04-28 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_merchant_available_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='available_balance',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payouts.payout'),
        ),
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together={('merchant', 'key')},
        ),
    ]
